AWSTemplateFormatVersion: '2010-09-09'
Description: KrishiMind AI Infrastructure

Parameters:
  S3BucketName:
    Type: String
    Default: krishimind-data
    Description: S3 bucket for data storage

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled

  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: KrishiMindAPI
      ProtocolType: HTTP

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt ApiGateway.ApiEndpoint
